### ISSUE TITLE
[patch] Allow on already-opened handles

### ISSUE THREAD

**Issue by jccleaver** [Leont/perlio-buffersize#1]
I can't speak for all cases, but your module seemed to be the ONLY thing (short of recompiling perl) capable of altering the read buffer size of STDIN in a post-perl 5.8.0 world. (The old setvbuf trick stopped working ages ago, and three days of Googling proved fruitless.)

We have a perl script that's dealing with large amounts of input being piped in, so closing and re-opening file handles didn't work for us; we needed to be able to operate on a handle already given to us.

This patch worked for me in that I was able to use:
    `binmode(STDIN, ":buffersize(65535)");`
... near the top of the script and an strace revealed my subsequent reads were for 64K instead of 4K. A great speed up!

```
--- PerlIO-buffersize-0.001-o4Qwjc/lib/PerlIO/buffersize.xs 2012-05-08 11:53:26.000000000 -0700
+++ PerlIO-buffersize-0.001-DZm2q3/lib/PerlIO/buffersize.xs 2015-04-14 12:06:49.000000000 -0700
@@ -8,11 +8,13 @@
    PerlIOBuf* buffer = PerlIOSelf(f, PerlIOBuf);
    if (!(PerlIOBase(f)->tab->kind & PERLIO_K_BUFFERED))
        Perl_warn(aTHX_ "Parent doesn't appear to be buffered, can't set buffer size");
-   else if (buffer->buf)
-       Perl_warn(aTHX_ "Can't set buffer size of handle that's already in use");
    else if (!arg || !SvOK(arg))
        Perl_warn(aTHX_ "No buffer size is given");
    else {
+       if (buffer->buf) {
+           Perl_warn(aTHX_ "Buffer of handle was already in use");
+           realloc(buffer->buf, SvIV(arg));
+       }
        buffer->bufsiz = SvIV(arg);
        return 0;
    }
```

**Comment by Leont** [comment]
Your request is reasonable, but your implementation is a bit buggy (one can't assume the buffer is allocated using malloc). I'll probably add something similar.

**Comment by jccleaver** [comment]
That would be awesome. Much appreciated!

**Comment by jccleaver** [comment]
Hi Leon,
Any chance you'd be able to get this ability into a release? It does happen to solve a specific niche use-case and I'd prefer to be able to point people to CPAN for the correct version.

**Comment by Leont** [comment]
Right, forgot about this. Will try to pick it up soon.

**Comment by jccleaver** [comment]
Sorry to keep poking, but the underlying use case hasn't changed :) 
Would love to get a reliable version of this in CPAN

**Comment by Leont** [comment]
I just released a version that can do this :-)
